/**
 * Ephemeris data (generated by scripts/fetch_data.py from NASA/JPL Horizons)
 * plus helpers for sampling positions at arbitrary times.
 *
 * Positions are heliocentric ecliptic J2000 in AU, velocities in AU/day,
 * sampled on a uniform Julian Date grid.
 */
import * as THREE from 'three';
import raw from '../data/ephemeris.json';

export type EventKind = 'perihelion' | 'approach' | 'conjunction' | 'node' | 'milestone';

export interface OrbitalElements {
  e: number;  // eccentricity
  a: number;  // semi-major axis (AU)
  i: number;  // inclination (deg)
  om: number; // longitude of ascending node (deg)
  w: number;  // argument of perihelion (deg)
}

export interface AtlasEvent {
  jd: number;
  date: string;
  title: string;
  detail: string;
  kind: EventKind;
}

export interface Body {
  id: string;
  name: string;
  color: string;
  elements?: OrbitalElements;
  pos: Float64Array; // [x0, y0, z0, x1, y1, z1, ...]
  vel: Float64Array;
}

export type Vec3 = [number, number, number];

interface RawData {
  meta: {
    source: string;
    frame: string;
    fetched: string;
    solution: string | null;
    observations: number | null;
    arc: [string | null, string | null];
    jd0: number;
    step: number;
    n: number;
  };
  bodies: { id: string; name: string; color: string; elements?: OrbitalElements; pos: number[]; vel: number[] }[];
  events: AtlasEvent[];
}

const data = raw as unknown as RawData;

export const AU_KM = 149597870.7;
export const meta = data.meta;
export const { jd0, step, n } = data.meta;
export const jdEnd = jd0 + step * (n - 1);
export const events: AtlasEvent[] = data.events;

export const bodies: Body[] = data.bodies.map(b => ({
  ...b,
  pos: Float64Array.from(b.pos),
  vel: Float64Array.from(b.vel),
}));
export const byId: Record<string, Body> = Object.fromEntries(bodies.map(b => [b.id, b]));

function locate(t: number): [k: number, s: number] {
  const s0 = (t - jd0) / step;
  const k = Math.min(Math.max(Math.floor(s0), 0), n - 2);
  return [k, Math.min(Math.max(s0 - k, 0), 1)];
}

/** Position at time t (JD) via cubic Hermite interpolation using the sampled velocities. */
export function positionAt(b: Body, t: number, out: Vec3 = [0, 0, 0]): Vec3 {
  const [k, s] = locate(t);
  const s2 = s * s, s3 = s2 * s;
  const h00 = 2 * s3 - 3 * s2 + 1, h10 = s3 - 2 * s2 + s, h01 = -2 * s3 + 3 * s2, h11 = s3 - s2;
  const a = 3 * k, c = 3 * (k + 1), P = b.pos, V = b.vel;
  for (let i = 0; i < 3; i++) {
    out[i] = h00 * P[a + i] + h10 * step * V[a + i] + h01 * P[c + i] + h11 * step * V[c + i];
  }
  return out;
}

/** Velocity at time t (AU/day), linearly interpolated. */
export function velocityAt(b: Body, t: number): Vec3 {
  const [k, s] = locate(t);
  const v = (i: number) => b.vel[3 * k + i] * (1 - s) + b.vel[3 * k + 3 + i] * s;
  return [v(0), v(1), v(2)];
}

/** Ecliptic (X, Y, Z) with Z = north  →  Three.js world (Y-up): (X, Z, -Y). */
export function toScene(e: ArrayLike<number>, v = new THREE.Vector3()): THREE.Vector3 {
  return v.set(e[0], e[2], -e[1]);
}

/** Scene-space position of a body at time t. */
export function scenePositionAt(b: Body, t: number, v = new THREE.Vector3()): THREE.Vector3 {
  return toScene(positionAt(b, t), v);
}

/** Scene-space position of the k-th raw sample. */
export function sampleScene(b: Body, k: number, v = new THREE.Vector3()): THREE.Vector3 {
  return v.set(b.pos[3 * k], b.pos[3 * k + 2], -b.pos[3 * k + 1]);
}

// ---------- time helpers ----------
export const jdToDate = (jd: number) => new Date((jd - 2440587.5) * 86400000);
export const dateToJd = (d: Date) => d.getTime() / 86400000 + 2440587.5;
export const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export function formatDate(jd: number, withTime = true): string {
  const d = jdToDate(jd);
  const date = `${d.getUTCDate()} ${MONTHS[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
  if (!withTime) return date;
  const hh = String(d.getUTCHours()).padStart(2, '0'), mm = String(d.getUTCMinutes()).padStart(2, '0');
  return `${date} ${hh}:${mm} UTC`;
}

const isoJd = (s: string | null, fallback: number) => (s ? dateToJd(new Date(`${s}T00:00Z`)) : fallback);
/** Span of observations used in JPL's orbit fit; outside it the path is extrapolated. */
export const arcStart = isoJd(meta.arc[0], jd0);
export const arcEnd = isoJd(meta.arc[1], jdEnd);
