/**
 * Ephemeris data (generated by scripts/fetch_data.py from NASA/JPL Horizons)
 * plus helpers for sampling positions at arbitrary times.
 *
 * Positions are heliocentric ecliptic J2000 in AU, velocities in AU/day, on uniform
 * Julian Date grids: a fine 12 h "near" segment (2024–2028, always loaded) and a
 * coarse 5 d "far" segment (2028–2090, lazy-loaded for long-range missions).
 */
import * as THREE from 'three';
import raw from '../data/ephemeris.json';

export type EventKind = 'perihelion' | 'approach' | 'conjunction' | 'node' | 'milestone';

export interface OrbitalElements {
  e: number;  // eccentricity
  a: number;  // semi-major axis (AU)
  i: number;  // inclination (deg)
  om: number; // longitude of ascending node (deg)
  w: number;  // argument of perihelion (deg)
}

export interface AtlasEvent {
  jd: number;
  date: string;
  title: string;
  detail: string;
  kind: EventKind;
}

interface Segment {
  jd0: number;
  step: number;
  n: number;
  pos: Float64Array; // [x0, y0, z0, x1, y1, z1, ...]
  vel: Float64Array;
}

export interface Body {
  id: string;
  name: string;
  color: string;
  elements?: OrbitalElements;
  segments: Segment[];
}

export type Vec3 = [number, number, number];

interface RawBody { id: string; pos: number[]; vel: number[] }
interface RawGrid { jd0: number; step: number; n: number }
interface RawData {
  meta: RawGrid & {
    source: string;
    frame: string;
    fetched: string;
    solution: string | null;
    observations: number | null;
    arc: [string | null, string | null];
  };
  bodies: (RawBody & { name: string; color: string; elements?: OrbitalElements })[];
  events: AtlasEvent[];
}

const data = raw as unknown as RawData;

export const AU_KM = 149597870.7;
export const meta = data.meta;
/** The always-loaded near range. */
export const jd0 = meta.jd0;
export const jdEnd = meta.jd0 + meta.step * (meta.n - 1);
export const events: AtlasEvent[] = data.events;

const segment = (grid: RawGrid, b: RawBody): Segment => ({
  jd0: grid.jd0, step: grid.step, n: grid.n, pos: Float64Array.from(b.pos), vel: Float64Array.from(b.vel),
});

export const bodies: Body[] = data.bodies.map(b => ({
  id: b.id, name: b.name, color: b.color, elements: b.elements, segments: [segment(meta, b)],
}));
export const byId: Record<string, Body> = Object.fromEntries(bodies.map(b => [b.id, b]));

// ---------- long-range data ----------
let farEnd: number | null = null;
let farLoading: Promise<void> | null = null;

/** Last Julian Date with data (grows once the far segment is loaded). */
export const dataEnd = () => farEnd ?? jdEnd;

/** Load the 2028–2090 segment (separate chunk, ~3 MB) if it isn't already. */
export function loadFar(): Promise<void> {
  farLoading ??= import('../data/ephemeris-far.json').then(mod => {
    const far = mod.default as unknown as { meta: RawGrid; bodies: RawBody[] };
    for (const fb of far.bodies) byId[fb.id]?.segments.push(segment(far.meta, fb));
    farEnd = far.meta.jd0 + far.meta.step * (far.meta.n - 1);
  });
  return farLoading;
}

// ---------- sampling ----------
function locate(b: Body, t: number): [Segment, number, number] {
  const segs = b.segments;
  let seg = segs[0];
  for (let i = 1; i < segs.length && t > seg.jd0 + seg.step * (seg.n - 1); i++) seg = segs[i];
  const s0 = (t - seg.jd0) / seg.step;
  const k = Math.min(Math.max(Math.floor(s0), 0), seg.n - 2);
  return [seg, k, Math.min(Math.max(s0 - k, 0), 1)];
}

/** Position at time t (JD) via cubic Hermite interpolation using the sampled velocities. */
export function positionAt(b: Body, t: number, out: Vec3 = [0, 0, 0]): Vec3 {
  const [seg, k, s] = locate(b, t);
  const { step, pos: P, vel: V } = seg;
  const s2 = s * s, s3 = s2 * s;
  const h00 = 2 * s3 - 3 * s2 + 1, h10 = s3 - 2 * s2 + s, h01 = -2 * s3 + 3 * s2, h11 = s3 - s2;
  const a = 3 * k, c = 3 * (k + 1);
  for (let i = 0; i < 3; i++) {
    out[i] = h00 * P[a + i] + h10 * step * V[a + i] + h01 * P[c + i] + h11 * step * V[c + i];
  }
  return out;
}

/** Velocity at time t (AU/day), linearly interpolated. */
export function velocityAt(b: Body, t: number): Vec3 {
  const [seg, k, s] = locate(b, t);
  const v = (i: number) => seg.vel[3 * k + i] * (1 - s) + seg.vel[3 * k + 3 + i] * s;
  return [v(0), v(1), v(2)];
}

/** Ecliptic (X, Y, Z) with Z = north  →  Three.js world (Y-up): (X, Z, -Y). */
export function toScene(e: ArrayLike<number>, v = new THREE.Vector3()): THREE.Vector3 {
  return v.set(e[0], e[2], -e[1]);
}

/** Scene-space position of a body at time t. */
export function scenePositionAt(b: Body, t: number, v = new THREE.Vector3()): THREE.Vector3 {
  return toScene(positionAt(b, t), v);
}

/** All raw samples of a body across loaded segments, as (jd, scene position) pairs. */
export function samples(b: Body): { jd: number; p: THREE.Vector3 }[] {
  const out: { jd: number; p: THREE.Vector3 }[] = [];
  for (const seg of b.segments) {
    const last = out.length ? out[out.length - 1].jd : -Infinity;
    for (let k = 0; k < seg.n; k++) {
      const jd = seg.jd0 + k * seg.step;
      if (jd <= last) continue; // segments share their boundary sample
      out.push({ jd, p: new THREE.Vector3(seg.pos[3 * k], seg.pos[3 * k + 2], -seg.pos[3 * k + 1]) });
    }
  }
  return out;
}

// ---------- time helpers ----------
export const jdToDate = (jd: number) => new Date((jd - 2440587.5) * 86400000);
export const dateToJd = (d: Date) => d.getTime() / 86400000 + 2440587.5;
export const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export function formatDate(jd: number, withTime = true): string {
  const d = jdToDate(jd);
  const date = `${d.getUTCDate()} ${MONTHS[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
  if (!withTime) return date;
  const hh = String(d.getUTCHours()).padStart(2, '0'), mm = String(d.getUTCMinutes()).padStart(2, '0');
  return `${date} ${hh}:${mm} UTC`;
}

const isoJd = (s: string | null, fallback: number) => (s ? dateToJd(new Date(`${s}T00:00Z`)) : fallback);
/** Span of observations used in JPL's orbit fit; outside it the path is extrapolated. */
export const arcStart = isoJd(meta.arc[0], jd0);
export const arcEnd = isoJd(meta.arc[1], jdEnd);
