/**
 * Hypothetical intercept missions (generated by scripts/missions.py).
 *
 * Each mission is a chain of Keplerian legs sampled densely near perihelion;
 * positions between samples are linearly interpolated.
 */
import * as THREE from 'three';
import raw from '../data/missions.json';
import { jdEnd } from './ephemeris';

export interface Burn {
  jd: number;
  date: string;
  body: string;
  dv: number;     // km/s
  label: string;
}

export interface Encounter {
  jd: number;
  date: string;
  rSun: number;     // AU
  rEarth: number;   // AU
  relSpeed: number; // km/s (0 = rendezvous)
}

interface Leg { t: number[]; p: number[] }

export interface Mission {
  id: string;
  name: string;
  /** paper = published study; computed = what-if solved here; rough = back-of-envelope idea */
  kind: 'paper' | 'computed' | 'rough';
  /** Set for missions not driven by rocket ΔV (e.g. a laser-pushed sail). */
  propulsion?: 'laser';
  summary: string;
  source?: { label: string; url: string };
  /** The published figures, when this is a reconstruction of a paper. */
  paper?: string;
  burns: Burn[];
  legs: Leg[];
  encounter: Encounter;
  stats: { vinf?: number; c3?: number; park?: string; perihelionSpeed?: number };
  totalDv: number;
}

export const missions: Mission[] = (raw as unknown as { missions: Mission[] }).missions;

export const launchJd = (m: Mission) => m.burns[0].jd;
export const needsFarData = (m: Mission) => m.encounter.jd > jdEnd;

/** Flattened (time, scene position) samples for a whole mission. */
export function pathSamples(m: Mission): { t: Float64Array; p: THREE.Vector3[] } {
  const ts: number[] = [], ps: THREE.Vector3[] = [];
  for (const leg of m.legs) {
    for (let i = 0; i < leg.t.length; i++) {
      if (ts.length && leg.t[i] <= ts[ts.length - 1]) continue;
      ts.push(leg.t[i]);
      ps.push(new THREE.Vector3(leg.p[3 * i], leg.p[3 * i + 2], -leg.p[3 * i + 1]));
    }
  }
  return { t: Float64Array.from(ts), p: ps };
}

/** Index of the last sample at or before t (binary search), or -1. */
export function sampleIndex(times: Float64Array, t: number): number {
  let lo = 0, hi = times.length - 1;
  if (t < times[0]) return -1;
  if (t >= times[hi]) return hi;
  while (hi - lo > 1) {
    const mid = (lo + hi) >> 1;
    if (times[mid] <= t) lo = mid; else hi = mid;
  }
  return lo;
}

/** Probe position at time t (clamped to launch / encounter). */
export function probePositionAt(path: { t: Float64Array; p: THREE.Vector3[] }, t: number, out = new THREE.Vector3()) {
  const k = sampleIndex(path.t, t);
  if (k < 0) return out.copy(path.p[0]);
  if (k >= path.t.length - 1) return out.copy(path.p[path.p.length - 1]);
  const s = (t - path.t[k]) / (path.t[k + 1] - path.t[k]);
  return out.lerpVectors(path.p[k], path.p[k + 1], s);
}
