/**
 * Real naked-eye sky from the Yale Bright Star Catalogue (generated by scripts/fetch_stars.py).
 * Stars sit on a large sphere that follows the camera, so they behave as if infinitely far away.
 */
import * as THREE from 'three';
import raw from '../data/stars.json';
import { toScene } from './ephemeris';

const SKY_RADIUS = 2000;
const MAG_LIMIT = 6.5;

/** Approximate star colour from the B-V colour index, softened toward white. */
function bvToRgb(bv: number): [number, number, number] {
  // B-V → effective temperature (Ballesteros 2012)
  const t = 4600 * (1 / (0.92 * bv + 1.7) + 1 / (0.92 * bv + 0.62));
  // Temperature → RGB (Tanner Helland's blackbody fit), in 0..1
  const k = t / 100;
  const r = k <= 66 ? 1 : Math.min(1, 1.2929 * Math.pow(k - 60, -0.1332));
  const g = k <= 66 ? Math.min(1, Math.max(0, 0.3901 * Math.log(k) - 0.6318)) : Math.min(1, 1.1299 * Math.pow(k - 60, -0.0755));
  const b = k >= 66 ? 1 : k <= 19 ? 0 : Math.min(1, Math.max(0, 0.5432 * Math.log(k - 10) - 1.1962));
  const mix = 0.55; // keep colours subtle, as the eye sees them
  return [r * mix + (1 - mix), g * mix + (1 - mix), b * mix + (1 - mix)];
}

const vertexShader = /* glsl */ `
  attribute float size;
  attribute vec3 color;
  varying vec3 vColor;
  uniform float pixelRatio;
  void main() {
    vColor = color;
    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
    gl_PointSize = size * pixelRatio;
  }
`;

const fragmentShader = /* glsl */ `
  varying vec3 vColor;
  void main() {
    // Bright core plus a soft halo. Additive blending already multiplies by alpha, so
    // the colour is left unscaled here.
    float d = length(gl_PointCoord - 0.5) * 2.0;
    float core = smoothstep(0.45, 0.0, d);
    float halo = pow(max(1.0 - d, 0.0), 2.0) * 0.45;
    float a = clamp(core + halo, 0.0, 1.0);
    if (a < 0.01) discard;
    gl_FragColor = vec4(vColor, a);
  }
`;

export function makeStarfield(camera: THREE.Camera, pixelRatio: number): THREE.Points {
  const stars = (raw as unknown as { stars: [number, number, number, number, number][] }).stars;
  const pos = new Float32Array(stars.length * 3);
  const col = new Float32Array(stars.length * 3);
  const size = new Float32Array(stars.length);
  const v = new THREE.Vector3();
  stars.forEach(([x, y, z, mag, bv], i) => {
    toScene([x, y, z], v).multiplyScalar(SKY_RADIUS).toArray(pos, i * 3);
    const brightness = MAG_LIMIT - mag; // 0 for the faintest, ~8 for Sirius
    size[i] = 2.5 + 0.28 * brightness * brightness;
    const intensity = Math.min(1, 0.4 + 0.16 * brightness);
    const [r, g, b] = bvToRgb(bv);
    col.set([r * intensity, g * intensity, b * intensity], i * 3);
  });
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
  geo.setAttribute('color', new THREE.BufferAttribute(col, 3));
  geo.setAttribute('size', new THREE.BufferAttribute(size, 1));
  const mat = new THREE.ShaderMaterial({
    vertexShader, fragmentShader,
    uniforms: { pixelRatio: { value: pixelRatio } },
    transparent: true, depthWrite: false, blending: THREE.AdditiveBlending,
  });
  const points = new THREE.Points(geo, mat);
  points.frustumCulled = false;
  // Keep stars "at infinity" by following the camera.
  points.onBeforeRender = () => points.position.copy(camera.position);
  return points;
}

// ---------- hover info for the brightest stars ----------

export interface NamedStar {
  /** Index into the star list (sorted brightest first, so also a brightness rank). */
  i: number;
  name: string;
  /** Bayer/Flamsteed designation when the star also has a proper name, e.g. "α Canis Majoris". */
  designation: string;
  constellation: string;
  mag: number;
  distLy: number | null;
}

const HOVER_RADIUS_PX = 10;
const ordinal = (n: number) => {
  const s = ['th', 'st', 'nd', 'rd'], v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
};

/** Shows a tooltip (and a ring) when the pointer is near one of the named bright stars. */
export class StarHover {
  private readonly named = (raw as unknown as { named: NamedStar[] }).named;
  private readonly ring = Object.assign(document.createElement('div'), { className: 'star-ring', hidden: true });
  private readonly v = new THREE.Vector3();
  private current: NamedStar | null = null;

  constructor(
    private readonly stars: THREE.Points,
    private readonly camera: THREE.Camera,
    canvas: HTMLElement,
    private readonly tooltip: HTMLElement,
    layer: HTMLElement,
  ) {
    layer.appendChild(this.ring);
    canvas.addEventListener('pointermove', ev => {
      if (ev.buttons !== 0 || ev.pointerType === 'touch') return this.hide();
      this.pick(ev.clientX, ev.clientY);
    });
    canvas.addEventListener('pointerdown', () => this.hide());
    canvas.addEventListener('pointerleave', () => this.hide());
    canvas.addEventListener('wheel', () => this.hide(), { passive: true });
  }

  private pick(mx: number, my: number) {
    const pos = this.stars.geometry.getAttribute('position');
    let best: NamedStar | null = null, bestD = HOVER_RADIUS_PX, bx = 0, by = 0;
    for (const s of this.named) {
      // Stars follow the camera, so world position = camera position + catalogue direction × radius
      this.v.fromBufferAttribute(pos, s.i).add(this.camera.position).project(this.camera);
      if (this.v.z > 1 || this.v.z < -1) continue;
      const x = (this.v.x * 0.5 + 0.5) * innerWidth, y = (-this.v.y * 0.5 + 0.5) * innerHeight;
      const d = Math.hypot(x - mx, y - my);
      if (d < bestD) { best = s; bestD = d; bx = x; by = y; }
    }
    if (!best) return this.hide();
    this.ring.hidden = false;
    this.ring.style.transform = `translate(${bx}px, ${by}px)`;
    if (best !== this.current) this.fill(best);
    this.current = best;
    const tip = this.tooltip, r = tip.getBoundingClientRect();
    tip.style.left = `${Math.min(Math.max(8, bx + 14), innerWidth - r.width - 8)}px`;
    tip.style.top = `${Math.min(Math.max(8, by - r.height / 2), innerHeight - r.height - 8)}px`;
  }

  private fill(s: NamedStar) {
    const line = (cls: string, text: string) => Object.assign(document.createElement('div'), { className: cls, textContent: text });
    const rows = [line('t', s.name)];
    rows.push(line('when', [s.designation, s.constellation].filter(Boolean).join(' · ')));
    rows.push(line('', `Magnitude ${s.mag.toFixed(2)} (${ordinal(s.i + 1)} brightest)`));
    if (s.distLy !== null) {
      const ly = s.distLy < 100 ? s.distLy.toFixed(1) : Math.round(s.distLy).toLocaleString();
      rows.push(line('', `${ly} light-years away`));
      const year = new Date().getUTCFullYear() - s.distLy;
      if (s.distLy >= 2) {
        rows.push(line('when', `The light you see left it ${year > 0 ? `around ${Math.round(year)}` : `around ${Math.round(-year)} BC`}`));
      }
    }
    this.tooltip.replaceChildren(...rows);
    this.tooltip.hidden = false;
  }

  private hide() {
    if (!this.current) return;
    this.current = null;
    this.ring.hidden = true;
    this.tooltip.hidden = true;
  }
}
