/**
 * Real naked-eye sky from the Yale Bright Star Catalogue (generated by scripts/fetch_stars.py).
 * Stars sit on a large sphere that follows the camera, so they behave as if infinitely far away.
 */
import * as THREE from 'three';
import raw from '../data/stars.json';
import { toScene } from './ephemeris';

const SKY_RADIUS = 2000;
const MAG_LIMIT = 6.5;

/** Approximate star colour from the B-V colour index, softened toward white. */
function bvToRgb(bv: number): [number, number, number] {
  // B-V → effective temperature (Ballesteros 2012)
  const t = 4600 * (1 / (0.92 * bv + 1.7) + 1 / (0.92 * bv + 0.62));
  // Temperature → RGB (Tanner Helland's blackbody fit), in 0..1
  const k = t / 100;
  const r = k <= 66 ? 1 : Math.min(1, 1.2929 * Math.pow(k - 60, -0.1332));
  const g = k <= 66 ? Math.min(1, Math.max(0, 0.3901 * Math.log(k) - 0.6318)) : Math.min(1, 1.1299 * Math.pow(k - 60, -0.0755));
  const b = k >= 66 ? 1 : k <= 19 ? 0 : Math.min(1, Math.max(0, 0.5432 * Math.log(k - 10) - 1.1962));
  const mix = 0.55; // keep colours subtle, as the eye sees them
  return [r * mix + (1 - mix), g * mix + (1 - mix), b * mix + (1 - mix)];
}

const vertexShader = /* glsl */ `
  attribute float size;
  attribute vec3 color;
  varying vec3 vColor;
  uniform float pixelRatio;
  void main() {
    vColor = color;
    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
    gl_PointSize = size * pixelRatio;
  }
`;

const fragmentShader = /* glsl */ `
  varying vec3 vColor;
  void main() {
    // Bright core plus a soft halo. Additive blending already multiplies by alpha, so
    // the colour is left unscaled here.
    float d = length(gl_PointCoord - 0.5) * 2.0;
    float core = smoothstep(0.45, 0.0, d);
    float halo = pow(max(1.0 - d, 0.0), 2.0) * 0.45;
    float a = clamp(core + halo, 0.0, 1.0);
    if (a < 0.01) discard;
    gl_FragColor = vec4(vColor, a);
  }
`;

export function makeStarfield(camera: THREE.Camera, pixelRatio: number): THREE.Points {
  const stars = (raw as unknown as { stars: [number, number, number, number, number][] }).stars;
  const pos = new Float32Array(stars.length * 3);
  const col = new Float32Array(stars.length * 3);
  const size = new Float32Array(stars.length);
  const v = new THREE.Vector3();
  stars.forEach(([x, y, z, mag, bv], i) => {
    toScene([x, y, z], v).multiplyScalar(SKY_RADIUS).toArray(pos, i * 3);
    const brightness = MAG_LIMIT - mag; // 0 for the faintest, ~8 for Sirius
    size[i] = 2.5 + 0.28 * brightness * brightness;
    const intensity = Math.min(1, 0.4 + 0.16 * brightness);
    const [r, g, b] = bvToRgb(bv);
    col.set([r * intensity, g * intensity, b * intensity], i * 3);
  });
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
  geo.setAttribute('color', new THREE.BufferAttribute(col, 3));
  geo.setAttribute('size', new THREE.BufferAttribute(size, 1));
  const mat = new THREE.ShaderMaterial({
    vertexShader, fragmentShader,
    uniforms: { pixelRatio: { value: pixelRatio } },
    transparent: true, depthWrite: false, blending: THREE.AdditiveBlending,
  });
  const points = new THREE.Points(geo, mat);
  points.frustumCulled = false;
  // Keep stars "at infinity" by following the camera.
  points.onBeforeRender = () => points.position.copy(camera.position);
  return points;
}
